subscription houseBets {
  houseBets {
    ...BetFragment
    __typename
  }
}

fragment BetFragment on Bet {
  id
  iid
  type
  scope
  game {
    name
    icon
    __typename
  }
  bet {
    ... on CasinoBet {
      ...CasinoBetFragment
      __typename
    }
    ... on MultiplayerCrashBet {
      ...MultiplayerCrashBet
      __typename
    }
    ... on MultiplayerSlideBet {
      ...MultiplayerSlideBet
      __typename
    }
    ... on SoftswissBet {
      ...SoftswissBet
      __typename
    }
    ... on SportBet {
      ...SportBet
      __typename
    }
    ... on EvolutionBet {
      ...EvolutionBet
      __typename
    }
    ... on PlayerPropBet {
      ...PlayerPropBetFragment
      __typename
    }
    __typename
  }
  __typename
}

fragment CasinoBetFragment on CasinoBet {
  id
  active
  payoutMultiplier
  amountMultiplier
  amount
  payout
  updatedAt
  currency
  game
  user {
    id
    name
    __typename
  }
  __typename
}

fragment MultiplayerCrashBet on MultiplayerCrashBet {
  id
  user {
    id
    name
    __typename
  }
  payoutMultiplier
  gameId
  amount
  payout
  currency
  result
  updatedAt
  cashoutAt
  btcAmount: amount(currency: btc)
  __typename
}

fragment MultiplayerSlideBet on MultiplayerSlideBet {
  id
  user {
    id
    name
    __typename
  }
  payoutMultiplier
  gameId
  amount
  payout
  currency
  slideResult: result
  updatedAt
  cashoutAt
  btcAmount: amount(currency: btc)
  active
  createdAt
  __typename
}

fragment SoftswissBet on SoftswissBet {
  id
  amount
  currency
  updatedAt
  payout
  payoutMultiplier
  user {
    id
    name
    __typename
  }
  softswissGame: game {
    id
    name
    edge
    extId
    provider {
      id
      name
      __typename
    }
    __typename
  }
  __typename
}

fragment SportBet on SportBet {
  id
  amount
  active
  currency
  status
  payoutMultiplier
  potentialMultiplier
  cashoutMultiplier
  payout
  createdAt
  user {
    id
    name
    __typename
  }
  outcomes {
    odds
    status
    outcome {
      id
      name
      active
      odds
      __typename
    }
    market {
      ...MarketFragment
      fixture {
        id
        tournament {
          id
          category {
            id
            sport {
              id
              slug
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    fixture {
      ...FixturePreviewFragment
      __typename
    }
    __typename
  }
  adjustments {
    id
    payoutMultiplier
    updatedAt
    createdAt
    __typename
  }
  __typename
}

fragment MarketFragment on SportMarket {
  id
  name
  status
  extId
  specifiers
  outcomes {
    id
    active
    name
    odds
    __typename
  }
  __typename
}

fragment FixturePreviewFragment on SportFixture {
  id
  extId
  status
  slug
  marketCount(status: [active, suspended])
  data {
    ...FixtureDataMatchFragment
    ...FixtureDataOutrightFragment
    __typename
  }
  eventStatus {
    ...FixtureEventStatus
    __typename
  }
  tournament {
    ...TournamentTreeFragment
    __typename
  }
  ...LiveStreamExistsFragment
  __typename
}

fragment FixtureDataMatchFragment on SportFixtureDataMatch {
  startTime
  competitors {
    ...CompetitorFragment
    __typename
  }
  __typename
}

fragment CompetitorFragment on SportFixtureCompetitor {
  name
  extId
  countryCode
  abbreviation
  __typename
}

fragment FixtureDataOutrightFragment on SportFixtureDataOutright {
  name
  startTime
  endTime
  __typename
}

fragment FixtureEventStatus on SportFixtureEventStatus {
  homeScore
  awayScore
  matchStatus
  clock {
    matchTime
    remainingTime
    __typename
  }
  periodScores {
    homeScore
    awayScore
    matchStatus
    __typename
  }
  currentServer {
    extId
    __typename
  }
  homeGameScore
  awayGameScore
  statistic {
    yellowCards {
      away
      home
      __typename
    }
    redCards {
      away
      home
      __typename
    }
    corners {
      home
      away
      __typename
    }
    __typename
  }
  __typename
}

fragment TournamentTreeFragment on SportTournament {
  id
  name
  slug
  category {
    id
    name
    slug
    sport {
      id
      name
      slug
      __typename
    }
    __typename
  }
  __typename
}

fragment LiveStreamExistsFragment on SportFixture {
  abiosStream {
    exists
    __typename
  }
  betradarStream {
    exists
    __typename
  }
  diceStream {
    exists
    __typename
  }
  __typename
}

fragment EvolutionBet on EvolutionBet {
  id
  amount
  currency
  createdAt
  payout
  payoutMultiplier
  user {
    id
    name
    __typename
  }
  softswissGame: game {
    id
    name
    edge
    __typename
  }
  __typename
}

fragment PlayerPropBetFragment on PlayerPropBet {
  active
  amount
  cashoutMultiplier
  createdAt
  currency
  id
  lineType
  odds
  payout
  payoutMultiplier
  updatedAt
  status
  user {
    id
    name
    __typename
  }
  playerPropLine {
    ...PlayerPropLineFragment
    __typename
  }
  __typename
}

fragment PlayerPropLineFragment on PlayerPropLine {
  id
  line
  over
  under
  suspended
  balanced
  name
  player {
    id
    name
    __typename
  }
  market {
    id
    stat {
      name
      value
      __typename
    }
    game {
      id
      fixture {
        id
        name
        data {
          ... on SportFixtureDataMatch {
            competitors {
              ...CompetitorFragment
              __typename
            }
            __typename
          }
          __typename
        }
        tournament {
          id
          category {
            id
            sport {
              id
              name
              slug
              __typename
            }
            __typename
          }
          __typename
        }
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}
