mutation MinesBet($amount: Float!, $currency: CurrencyEnum!, $minesCount: Int!, $fields: [Int!], $identifier: String) {
  minesBet(amount: $amount, currency: $currency, minesCount: $minesCount, fields: $fields, identifier: $identifier) {
    ...CasinoBetFragment
    state {
      ...MinesStateFragment
      __typename
    }
    __typename
  }
}

fragment CasinoBetFragment on CasinoBet {
  id
  active
  payoutMultiplier
  amountMultiplier
  amount
  payout
  updatedAt
  currency
  game
  user {
    id
    name
    __typename
  }
  __typename
}

fragment MinesStateFragment on CasinoGameMines {
  mines
  minesCount
  rounds {
    field
    payoutMultiplier
    __typename
  }
  __typename
}
