mutation slotBet($amount: Float!, $lines: Int!, $currency: CurrencyEnum!, $identifier: String!) {
  slotsBet(amount: $amount, currency: $currency, lines: $lines, identifier: $identifier) {
    ...CasinoBetFragment
    state {
      ...SlotsStateFragment
      __typename
    }
    __typename
  }
}

fragment CasinoBetFragment on CasinoBet {
  id
  active
  payoutMultiplier
  amountMultiplier
  amount
  payout
  updatedAt
  currency
  game
  user {
    id
    name
    __typename
  }
  __typename
}

fragment SlotsStateFragment on CasinoGameSlots {
  lines
  rounds {
    offsets
    paylines {
      payline
      hits
      multiplier
      symbol
      __typename
    }
    scatterMultiplier
    roundMultiplier
    totalMultiplier
    bonusRemaining
    bonusTotal
    __typename
  }
  __typename
}
